eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 0
spring:
#  application:
#    zipkin: http://localhost:9411
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/springboot-microservices-realm
