eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 0
spring:
#  application:
#    zipkin: http://localhost:9411
  cloud:
    vault:
      application-name: product-microservice
      authentication: TOKEN
      host: localhost
      port: 8200
      scheme: http
      token: hvs.c1mHXlUH13fC5YousBT78MZI
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090/realms/springboot-microservices-realm
