eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
spring:
  application:
    name: gateway-service
    zipkin: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          predicates:
            - Path=/api/products/**,/api/categories/**
          uri: lb://PRODUCT-SERVICE
        - id: order-service
          predicates:
            - Path=/api/orders/**
          uri: lb://ORDER-SERVICE
        - id: stock-service
          predicates:
            - Path=/api/stocks/**
          uri: lb://STOCK-SERVICE
        - id: auth-service
          predicates:
              - Path=/api/v1/auth/**
          uri: lb://AUTH-SERVICE
    loadbalancer:
      ribbon:
        enabled: false
