server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master
          search-paths: config-data
          uri: https://github.com/dreyesrod/springboot-microservices
