server:
    port: 8888
spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                native:
                    searchLocations: file:///D:/workspaces/es.dreyesr/springboot-microservices/config-data
#                git:
#                    clone-on-start: true
#                    uri: https://github.com/dreyesrod/service-configuration
